[package]
name = "rustychain"
version = "0.1.0"
authors = ["Andrew Fields <andybug10@gmail.com>"]

[dependencies]
serde = "1.0.14"
serde_derive = "1.0.14"
serde_yaml = "0.7.1"
byteorder = "1.1.0"
rust-crypto = "0.2.36"