[package]
name = "rustychain"
version = "0.1.0"
authors = ["Andrew Fields <andybug10@gmail.com>"]

[dependencies]
rustc-serialize = "*"
bincode = "*"
serde = "*"
serde_derive = "*"
#time = "0.1"
#byteorder = "1.1.0"
rust-crypto = "*"